[package]
name = "trait-tactics"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.12.1"
proc-macro2 = "1.0.79"
quote = "1.0.35"
syn = { version = "2.0.53", features = ["full"] }

[lib]
proc-macro = true
