[workspace.package]
version = "0.1.0"
edition = "2021"

[package]
name = "trait-tactics"
version.workspace = true
edition.workspace = true

[dependencies]
num-traits = "0.2.18"
trait-tactics-macros = { path = "macros" }
